image: atlassian/default-image:3

pipelines:
  branches:
    master:
      - step:
          name: Build Hugo
          script:
            - apt-get update -y && apt-get install wget
            - apt-get -y install git
            - wget https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_linux-amd64.deb
            - dpkg -i hugo*.deb
            - npm install -D
            - git submodule update --init --recursive
            - hugo --minify
          artifacts:
            - public/**
      - step:
          name: Deploy artifacts
          deployment: production
          script:
            - pipe: atlassian/google-cloud-storage-deploy:1.2.0
              variables:
                KEY_FILE: $GCS_KEY
                PROJECT: 'mlops-framework'
                BUCKET: 'documentation-site'
                SOURCE: 'public/*'